name 'dhoppe-apticron'
version '0.0.12'

author 'Dennis Hoppe'
license 'GPLv2'
project_page 'http://github.com/dhoppe/puppet-apticron'
source 'git://github.com/dhoppe/puppet-apticron'
summary 'Apticron Module'
description 'Apticron Module for Debian, Ubuntu'
dependency 'dhoppe/puppet', '>=0.0.1'
